import urllib2
import musixmatch
from urllib2 import Request, urlopen, URLError
import  xml.etree
import lxml
from lxml import objectify


def get_lyrics(artist, track):
	format = '&format=xml'
	request = 'http://api.musixmatch.com/ws/1.1/matcher.lyrics.get?q_track=' +track + '&q_artist=' +artist+ '&apikey=16fdae5bf1aed25e5a2fb06ce16045a8' +format
	response = urlopen(request)
	data = response.read()
	#song =  xml.etree.ElementTree.XML(data)
	song = objectify.fromstring(data)
	lyrics_val = song.body.lyrics.lyrics_body
	return lyrics_val


#get_lyrics("Walk-The-Moon","Shut-Up-and-Dance")
#get_lyrics("Justin-Bieber","No-Pressure")
#get_lyrics("Sia","Alive")
#get_lyrics("Brothers-Osborne","Stay-a-Little-Longer")
#get_lyrics("Selena-Gomez","Good-For-You")
#get_lyrics("Drake","Right-Hand")
#get_lyrics("Nathaniel-Rateliff","S.O.B.")
#get_lyrics("Jana-Kramer","I-Got-the-Boy")

#get_lyrics("Justin-Bieber","I'll-Show-You")
#get_lyrics("Coldplay","Adventure-of-a-Lifetime")
#get_lyrics("Justin-Bieber","The-Feeling")
#get_lyrics("Sam-Smith","Writing's-On-the-Wall")
#get_lyrics("Justin-Bieber","Purpose")
#get_lyrics("Drake","Jumpman")
#get_lyrics("Macklemore","Downtown")

#get_lyrics("The-Weeknd","Can't-Feel-My-Face")
#get_lyrics("X-Ambassadors","Renegades")
#get_lyrics("R-City","Locked-Away")
#get_lyrics("Rudimental","Lay-It-All-On-Me")
#get_lyrics("iLoveMemphis","Hit-the-Quan")

#get_lyrics("Rachel-Platten","Fight-Song")
#get_lyrics("The-Chainsmokers","Roses")

#get_lyrics("Calvin-Harris","How-Deep-Is-Your-Love")
#get_lyrics("Zac-Brown-Band","Beautiful-Drug")
#get_lyrics("twenty-one-pilots","Stressed-Out")
#get_lyrics("Meghan-Trainor","Better-When-I'm-Dancin'")
#get_lyrics("Old-Dominion","Break-Up-with-Him")
#get_lyrics("Carrie-Underwood","Smoke-Break")
#get_lyrics("Rachel-Platten","Stand-By-You")
#get_lyrics("Nelly","The-Fix")
#get_lyrics("James-Bay","Let-It-Go")
#get_lyrics("Justin-Bieber","Mark-My-Words")
#get_lyrics("Ed-Sheeran","Photograph")
#get_lyrics("Disclosure","Magnets")

#get_lyrics("Eric-Church","Mr-Misunderstood")
#get_lyrics("Fall-Out-Boy","Uma-Thurman")
#get_lyrics("One-Direction","If-I-Could-Fly")
#get_lyrics("Ed-Sheeran","Thinking-Out-Loud")
#get_lyrics("Gwen-Stefani","Used-To-Love-You")
#get_lyrics("Tory-Lanez","Say-It")
#get_lyrics("Omi","Cheerleader")
#get_lyrics("Mark-Ronson","Uptown-Funk")
#get_lyrics("Nick-Jonas","Levels")
#get_lyrics("Justin-Bieber","Company")
#get_lyrics("Charlie-Puth","Marvin-Gaye")
#get_lyrics("Dion","The-Wanderer")
#get_lyrics("Mariah-Carey","All-I-Want-for-Christmas-Is-You")

#get_lyrics("One-Direction","A.M.")
#get_lyrics("Audien","Something-Better")
#get_lyrics("DNCE","Cake-By-the-Ocean")
#get_lyrics("Justin-Bieber","Life-Is-Worth-Living")
#get_lyrics("Justin-Bieber","Children")
#get_lyrics("Randy-Houser","We-Went")
#get_lyrics("One-Direction","History")
# get_lyrics("G-Eazy","Random")
#get_lyrics("John-Lennon","Imagine")
l147 = str(get_lyrics("Chris-Brown","Back-To-Sleep")) 
f = open('l147.txt','w')
f.write(l147) 
f.close()

l148 = str(get_lyrics("Wes-Walker","Jordan-Belfort"))
l149 = str(get_lyrics("Jordan-Smith","Halo"))
l150 = str(get_lyrics("Alabama-Shakes","Sound-&-Color"))

f = open('l148.txt','w')
f.write(l148) 
f.close()

f = open('l149.txt','w')
f.write(l148) 
f.close()

f = open('l150.txt','w')
f.write(l150) 
f.close()

l151 = str(get_lyrics("One-Direction","What-a-Feeling"))
l152 = str(get_lyrics("Elton-John","Your-Song"))
l153 = str(get_lyrics("Sheryl-Crow","Picture"))
l154 = str(get_lyrics("Cole-Swindell","Let-Me-See-Ya-Girl"))
l155 = str(get_lyrics("Andy-Grammer","Honey,-I'm-Good."))
l156 = str(get_lyrics("One-Direction","Wolves"))
l157 = str(get_lyrics("Charlie-Puth","One-Call-Away"))
l158 = str(get_lyrics("Pentatonix","Can't-Sleep-Love"))
l159 = str(get_lyrics("Chris-Stapleton","Nobody-To-Blame"))
l160 = str(get_lyrics("Adele","Someone-Like-You"))
l161 = str(get_lyrics("Tim-McGraw","Top-of-the-World"))
l162 = str(get_lyrics("Jordan-Feliz","The-River"))
l163 = str(get_lyrics("Jason-Derulo","Want-to-Want-Me"))
l164 = str(get_lyrics("Florida-Georgia-Line","Confession"))
l165 = str(get_lyrics("Hozier","Someone-New"))

f = open('l151.txt','w')
f.write(l151)
f.close()

f = open('l152.txt','w')
f.write(l152)
f.close()

f = open('l153.txt','w')
f.write(l153)
f.close()

f = open('l154.txt','w')
f.write(l154)
f.close()

f = open('l155.txt','w')
f.write(l155)
f.close()

f = open('l156.txt','w')
f.write(l156)
f.close()

f = open('l157.txt','w')
f.write(l157)
f.close()

f = open('l158.txt','w')
f.write(l158)
f.close()

f = open('l159.txt','w')
f.write(l159)
f.close()

f = open('l160.txt','w')
f.write(l160)
f.close()

f = open('l161.txt','w')
f.write(l161)
f.close()

f = open('l162.txt','w')
f.write(l162)
f.close()

f = open('l163.txt','w')
f.write(l163)
f.close()

f = open('l164.txt','w')
f.write(l164)
f.close()

f = open('l165.txt','w')
f.write(l165)
f.close()

l166 = str(get_lyrics("The-Weeknd","The-Hills-(Remix)"))
l167 = str(get_lyrics("One-Direction","I-Want-to-Write-You-a-Song"))
l168 = str(get_lyrics("Usher","Yeah!"))
l169 = str(get_lyrics("One-Direction","Temporary-Fix"))
l170 = str(get_lyrics("Justin-Bieber","Sorry-(Latino-Remix)"))
l171 = str(get_lyrics("Hailee-Steinfeld","Love-Myself"))
l172 = str(get_lyrics("Maroon-5","Sugar"))
l173 = str(get_lyrics("Taylor-Swift","Blank-Space"))
l174 = str(get_lyrics("The-Weeknd","Earned-It"))
l175 = str(get_lyrics("Jason-Aldean","Gonna-Know-We-Were-Here"))
l176 = str(get_lyrics("Ed-Sheeran","I-See-Fire"))
l177 = str(get_lyrics("Fall-Out-Boy","Centuries"))
l178 = str(get_lyrics("Luke-Bryan","Home-Alone-Tonight"))
l179 = str(get_lyrics("Drake","Energy"))
l180 = str(get_lyrics("Whitney-Houston","I-Wanna-Dance-With-Somebody"))

f = open('l166.txt','w')
f.write(l166)
f.close()
f = open('l167.txt','w')
f.write(l167)
f.close()
f = open('l168.txt','w')
f.write(l168)
f.close()
f = open('l169.txt','w')
f.write(l169)
f.close()
f = open('l170.txt','w')
f.write(l170)
f.close()
f = open('l171.txt','w')
f.write(l171)
f.close()
f = open('l172.txt','w')
f.write(l172)
f.close()
f = open('l173.txt','w')
f.write(l173)
f.close()
f = open('l174.txt','w')
f.write(l174)
f.close()
f = open('l175.txt','w')
f.write(l175)
f.close()
f = open('l176.txt','w')
f.write(l176)
f.close()
f = open('l177.txt','w')
f.write(l177)
f.close()
f = open('l178.txt','w')
f.write(l178)
f.close()
f = open('l179.txt','w')
f.write(l179)
f.close()
f = open('l180.txt','w')
f.write(l180)
f.close()


l181 = str(get_lyrics("Panic!-At-the-Disco","Emperor's-New-Clothes"))
l182 = str(get_lyrics("Chris-Janson","Buy-Me-a-Boat"))
l183 = str(get_lyrics("Dierks-Bentley","Riser"))
l184 = str(get_lyrics("Alabama-Shakes","Sound-&-Color"))
l185 = str(get_lyrics("Coleman-Hell","2-Heads"))
l186 = str(get_lyrics("Jordan-Smith","Halo"))
l187 = str(get_lyrics("Troye-Sivan","Youth"))
l188 = str(get_lyrics("Justin-Bieber","Been-You"))
l189 = str(get_lyrics("Taylor-Swift","Shake-It-Off"))
l190 = str(get_lyrics("Snow-Patrol","Chasing-Cars"))
l191 = str(get_lyrics("Dan","Nothin'-Like-You"))
l192 = str(get_lyrics("Disclosure","Omen"))
l193 = str(get_lyrics("Hailee-Steinfeld","You're-Such-A"))
l194 = str(get_lyrics("One-Direction","Love-You-Goodbye"))
l195 = str(get_lyrics("Halsey","New-Americana"))

f = open('l181.txt','w')
f.write(l181)
f.close()
f = open('l182.txt','w')
f.write(l182)
f.close()
f = open('l183.txt','w')
f.write(l183)
f.close()
f = open('l184.txt','w')
f.write(l184)
f.close()
f = open('l185.txt','w')
f.write(l185)
f.close()
f = open('l186.txt','w')
f.write(l186)
f.close()
f = open('l187.txt','w')
f.write(l187)
f.close()
f = open('l188.txt','w')
f.write(l188)
f.close()
f = open('l189.txt','w')
f.write(l189)
f.close()
f = open('l190.txt','w')
f.write(l190)
f.close()
f = open('l191.txt','w')
f.write(l191)
f.close()
f = open('l192.txt','w')
f.write(l192)
f.close()
f = open('l193.txt','w')
f.write(l193)
f.close()
f = open('l194.txt','w')
f.write(l194)
f.close()
f = open('l195.txt','w')
f.write(l195)
f.close()

l196 = str(get_lyrics("Felly","Probation"))
l197 = str(get_lyrics("Afroman","Palmdale"))
l198 = str(get_lyrics("Stunt-Taylor","Fefe-On-The-Block"))
l199 = str(get_lyrics("Halsey","Colors"))
l200 = str(get_lyrics("Fall-Out-Boy","Centuries"))

f = open('l196.txt','w')
f.write(l196)
f.close()
f = open('l197.txt','w')
f.write(l197)
f.close()
f = open('l198.txt','w')
f.write(l198)
f.close()
f = open('l199.txt','w')
f.write(l199)
f.close()
f = open('l200.txt','w')
f.write(l200)
f.close()


