import numpy as np

def readSentimentList(file_name):
    ifile = open(file_name, 'r')
    happy_log_probs = {}
    sad_log_probs = {}
    ifile.readline() #Ignore title row
    
    for line in ifile:
        tokens = line[:-1].split(',')
        happy_log_probs[tokens[0]] = float(tokens[1])
        sad_log_probs[tokens[0]] = float(tokens[2])

    return happy_log_probs, sad_log_probs

def classifySentiment(words, happy_log_probs, sad_log_probs):
    # Get the log-probability of each word under each sentiment
    happy_probs = [happy_log_probs[word] for word in words if word in happy_log_probs]
    sad_probs = [sad_log_probs[word] for word in words if word in sad_log_probs]

    # Sum all the log-probabilities for each sentiment to get a log-probability for the whole tweet
    tweet_happy_log_prob = np.sum(happy_probs)
    tweet_sad_log_prob = np.sum(sad_probs)

    # Calculate the probability of the tweet belonging to each sentiment
    prob_happy = np.reciprocal(np.exp(tweet_sad_log_prob - tweet_happy_log_prob) + 1)
    prob_sad = 1 - prob_happy

    return prob_happy, prob_sad

def classifySentiment_workout(words, workout_log_probs, chill_log_probs):
    # Get the log-probability of each word under each sentiment
    workout_probs = [workout_log_probs[word] for word in words if word in workout_log_probs]
    chill_probs = [chill_log_probs[word] for word in words if word in chill_log_probs]

    # Sum all the log-probabilities for each sentiment to get a log-probability for the whole tweet
    tweet_workout_log_prob = np.sum(workout_probs)
    tweet_chill_log_prob = np.sum(chill_probs)

    # Calculate the probability of the tweet belonging to each sentiment
    prob_workout = np.reciprocal(np.exp(tweet_chill_log_prob - tweet_workout_log_prob) + 1)
    prob_chill = 1 - prob_workout

    return prob_workout, prob_chill

def main():
    # We load in the list of words and their log probabilities
    #25
    happy_log_probs, sad_log_probs = readSentimentList('twitter_sentiment_list.csv')
    workout_log_probs, chill_log_probs = readSentimentList('chill_sentiment_list.csv')

    # tweet1 = ['She', 'said',' to',' me',' Go',' steady',' on ','me']
    # tweet2 = ['Wont',' you',' tell',' me',' what',' the',' Wise',' Men',' said']
    # tweet3 = [ ' When',' they',' came',' down',' from',' Heaven']
    # tweet4 = ['Smoked ','nine',' til',' seven']
    # tweet5 = ['All',' the',' shit ','that ','they',' could',' find']
    # tweet6 = ['But',' they',' couldnt ','escape',' from',' you']
    # tweet7 = ['Couldnt',' be ','free ','of ','you']
    # tweet8 = ['And',' now',' they',' know ','theres',' no',' way',' out']
    # tweet9 = ['And',' theyre',' really ','sorry',' now',' for',' what',' theyve ','done']
    # tweet10 =['  They',' were ','three',' Wise',' Men',' just',' trying',' to',' have',' some',' fun']
    # tweet11 =[' Look ','whos',' alone ','now']
    # tweet12 =[' Its ','not',' me',' Its',' not',' me']
    # tweet13 =['Those',' three ','Wise',' Men']
    # tweet14 =['Theyve ','got',' a ','semi',' by ','the',' sea']
    # tweet15 =['Got',' to ','ask ','yourself ','the', 'question']
    # tweet16 =['Where','are',' you',' now']
    # tweet17 =['Got',' to',' ask',' yourself',' the',' question']

    # tweet1 = ['Im ','tired ','of ','being',' what',' you',' want',' me ','to ','be']
    # tweet2 = ['Feeling',' so ','faithless',' lost',' under ','the ','surface']
    # tweet3 = [ 'Dont',' know',' what',' youre',' expecting',' of',' me']
    # tweet4 = ['Put',' under',' the',' pressure ','of',' walking',' in ','your ','shoes']
    # tweet5 = ['Caught',' in',' the',' undertow',' just',' caught ','in ','the',' undertow']
    # tweet6 = ['Every',' step',' that ','I ','take ','is ','another mistake',' to',' you']
    # tweet7 = ['Caught',' in ','the ','undertow',' just ','caught',' in ','the ','undertow']
    # tweet8 = ['Ive',' become',' so',' numb']
    # tweet9 = ['I ','cant ','feel',' you',' there']
    # tweet10 =['Ive',' become',' so',' tired']
    # tweet11 =[' So',' much',' more ','aware']
    # tweet12 =[' Im',' becoming',' this']
    # tweet13 =['All',' I ','want ','to',' do']
    # tweet14 =['Is',' be',' more',' like',' me']
    # tweet15 =['And',' be ','less ','like',' you']
    # tweet16 =['Can',' you',' see',' that',' youre ','smothering ','me']
    # tweet17 =['Ooh']

    # tweet1 = ['Yeah']
    # tweet2 = ['I',' know ','sometimes',' things',' may',' not',' always',' make ','sense',' to ','you ','right',' now']
    # tweet3 = [ 'But',' hey',' what',' daddy',' always ','tell ','you']
    # tweet4 = ['Straighten ','up ','little ','soldier']
    # tweet5 = ['Stiffen',' up ','that upper',' lip']

    # tweet6 = ['What ','you ','crying',' about']
    # tweet7 = ['You',' got',' me']
    # tweet8 = ['Hailie',' I ','know you ','miss',' your',' mom']
    # tweet9 = ['And ','I',' know',' you',' miss',' your',' dad',' when',' Im',' gone']
    # tweet10 =['But',' Im ','trying ','to ','give ','you',' the',' life ','that',' I ','never',' had']

    # tweet11 =['I ','can ','see',' youre',' sad']
    # tweet12 =['Even',' when ','you ','smile']

    # tweet13 =['Even ','when',' you ','laugh']
    # tweet14 =['I ','can ','see ','it',' in ','your ','eyes']
    # tweet15 =['Deep ','inside',' you ','wanna',' cry']
    # tweet16 =['Cuz ','youre',' scared']
    # tweet17 =['I ','aint ','there']


    # tweet1 = ['Remy',' Boyz',' yeaahhhh']
    # tweet2 = ['1738']
    # tweet3 = ['Im ','like',' hey',' whats',' up',' hello']
    # tweet4 = ['Seen',' yo ','pretty ','ass',' soon',' as ','you',' came ','in',' that',' door']
    # tweet5 = ['I ','just ','wanna ','chill',' got',' a ','sack ','for ','us',' to ','roll']
    # tweet6 = ['Married',' to ','the',' money',' introduced ','her ','to',' my ','stove']
    # tweet7 = ['Showed',' her ','how',' to',' whip',' it',' now ','she ','remixin',' for',' low']
    # tweet8 = ['She ','my ','trap ','queen',' let ','her',' hit',' the',' bando']
    # tweet9 = ['We ','be',' countin',' up',' watch ','how ','far ','them',' bands',' go']
    # tweet10 = ['We ','just',' set ','a ','goal',' talkin',' matchin',' Lambos']
    # tweet11 = ['Got ','50',' 60 ','grand',' 500',' grams ','though']
    # tweet12 = ['Man',' I ','swear',' I ','love ','her',' how ','she ','work ','the ','damn',' pole']
    # tweet13 = ['Hit ','the ','strip ','club',' we',' be ','letting bands go']
    # tweet14 = ['Everybody ','hating',' we',' just',' call ','them ','fans ','though']
    # tweet15 = ['In',' love',' with',' the ','money',' I ','aint',' never ','letting',' go']
    # tweet16 = ['And ','I',' get',' high',' with',' my ','baby']
    # tweet17 = ['I ','just ','left ','the ','mall',' Im',' gettin',' fly ','with ','my ','baby']

    # tweet1 = ['Look', 'at ','the' ,'stars']
    # tweet2 =['Look', ' how' , ' they' , 'shine', ' for', 'you']
    # tweet3 = ['And', '  everything', '  you', '  do']
    # tweet4 = ['Yeah', ' they', '  were', '  all', ' yellow']
    # tweet5 = ['I', ' came', ' along']
    # tweet6 = ['I', ' wrote', ' a ', 'song', ' for', ' you']
    # tweet7 = ['And ', 'all', ' the', ' things', ' you', ' do']
    # tweet8 = ['And ', 'it', ' was', ' called', ' Yellow']
    # tweet9 = ['So', ' then', ' I', ' took', ' my', ' turn']
    # tweet10 = ['Oh', ' what', ' a', ' thing', ' to ve', ' done']
    # tweet11 = ['And', ' it', ' was', ' all', ' yellow']
    # tweet12 = ['Your', ' skin']
    # tweet13 = ['Oh', ' yeah', ' your', ' skin', ' and', ' bones']
    # tweet14 = ['Oh', ' yeah', ' your', ' skin', ' and', ' bones']
    # tweet15 = ['So', ' then', ' I', ' took', ' my', ' turn']
    # tweet16 = ['Oh', ' what', ' a', ' thing', ' to ve', ' done']
    # tweet17 = ['I', ' came', ' along']

    # tweet1 = ['Hello', 'darkness,', 'my', 'old', 'friend']
    # tweet2 = ['']
    # tweet3 = ["I've", 'come', 'to', 'talk', 'with', 'you', 'again']
    # tweet4 = ['']
    # tweet5 = ['Because', 'a', 'vision', 'softly', 'creeping']
    # tweet6 = ['Left', 'its', 'seeds', 'while', 'I', 'was', 'sleeping']
    # tweet7 = ['And', 'the', 'vision', 'that', 'was', 'planted', 'in', 'my', 'brain']
    # tweet8 = ['Still', 'remains']
    # tweet9 = ['Within', 'the', 'sound', 'of', 'silence.']
    # tweet10 = ['In', 'restless', 'dreams', 'I', 'walked', 'alone']
    # tweet11 = ['Narrow', 'streets', 'of', 'cobblestone']
    # tweet12 = ['']
    # tweet13 = ["'Neath", 'the', 'halo', 'of', 'a', 'street', 'lamp']
    # tweet14 = ['...']
    # tweet15 = ['']
    # tweet16 = ['']
    # tweet17 = ['...']

    # tweet1 = ['Follow', 'the', 'Moskwa']
    # tweet2 = ['Down', 'to', 'Gorky', 'Park']
    # tweet3 = ['Listening', 'to', 'the', 'wind', 'of', 'change']
    # tweet4 = ['An', 'August', 'summer', 'night']
    # tweet5 = ['Soldiers', 'passing', 'by']
    # tweet6 = ['Listening', 'to', 'the', 'wind', 'of', 'change']
    # tweet7 = ['']
    # tweet8 = ['The', 'world', 'is', 'closing', 'in']
    # tweet9 = ['Did', 'you', 'ever', 'think']
    # tweet10 = ['That', 'we', 'could', 'be', 'so', 'close,', 'like', 'brothers']
    # tweet11 = ['The', "future's", 'in', 'the', 'air']
    # tweet12 = ['Can', 'feel', 'it', 'everywhere']
    # tweet13 = ['Blowing', 'with', 'the', 'wind', 'of', 'change']
    # tweet14 = ['']
    # tweet15 = ['Take', 'me', 'to', 'the', 'magic', 'of', 'the', 'moment']
    # tweet16 = ['On', 'a', 'glory', 'night']
    # tweet17 = ['Where', 'the', 'children', 'of', 'tomorrow', 'dream', 'away']

    # tweet1 = ['Sorry', 'to', 'disturb', 'you']
    # tweet2 = ['But', 'I', 'was', 'in', 'the', 'neighborhood']
    # tweet3 = ['About', 'a', 'friend,', "I've", 'her', 'picture']
    # tweet4 = ['Could', 'you', 'take', 'a', 'look?']
    # tweet5 = ['']
    # tweet6 = ['Oh,', 'I', 'appreciate', "you're", 'busy']
    # tweet7 = ['And', 'time', 'is', 'not', 'your', 'own']
    # tweet8 = ['Yeah,', 'maybe', 'it', 'would', 'be', 'better']
    # tweet9 = ['If', 'I', 'telephoned']
    # tweet10 = ['']
    # tweet11 = ['Carrie', "doesn't", 'live', 'here', 'anymore']
    # tweet12 = ['(Carrie)']
    # tweet13 = ['Carrie', 'used', 'to', 'room', 'on', 'the', 'second', 'floor']
    # tweet14 = ['(On', 'the', 'second)']
    # tweet15 = ['Sorry', 'that', 'she', 'left', 'no', 'forwarding', 'address']
    # tweet16 = ['That', 'was', 'known', 'to', 'me']
    # tweet17 = ['...']

    # tweet1 = ['Tell', 'me', 'what', 'you', 'want']
    # tweet2 = ['What', 'you', 'like']
    # tweet3 = ["It's", 'okay']
    # tweet4 = ["I'mma", 'little', 'curious,', 'too']
    # tweet5 = ['Tell', 'me', 'if', "it's", 'wrong']
    # tweet6 = ['If', "it's", 'right']
    # tweet7 = ['I', "don't", 'care']
    # tweet8 = ['I', 'can', 'keep', 'a', 'secret,', 'can', 'you?']
    # tweet9 = ["We're", 'cool', 'for', 'the', 'summer']
    # tweet10 = ['Got', 'my', 'mind', 'on', 'your', 'body']
    # tweet11 = ['And', 'your', 'body', 'on', 'my', 'mind']
    # tweet12 = ['Got', 'a', 'taste', 'for', 'the', 'cherry']
    # tweet13 = ['I', 'just', 'need', 'to', 'take', 'a', 'bite']
    # tweet14 = ['']
    # tweet15 = ["Don't", 'tell', 'your', 'mother']
    # tweet16 = ['Kiss', 'one', 'another']
    # tweet17 = ['Die', 'for', 'each', 'other']

    # tweet1 = ['In', 'the', 'town', 'where', 'I', 'was', 'born']
    # tweet2 = ['Lived', 'a', 'man', 'who', 'sailed', 'to', 'sea']
    # tweet3 = ['And', 'he', 'told', 'us', 'of', 'his', 'life']
    # tweet4 = ['In', 'the', 'land', 'of', 'submarines']
    # tweet5 = ['']
    # tweet6 = ['So', 'we', 'sailed', 'up', 'to', 'the', 'sun']
    # tweet7 = ['Till', 'we', 'found', 'the', 'sea', 'of', 'green']
    # tweet8 = ['And', 'we', 'lived', 'beneath', 'the', 'waves']
    # tweet9 = ['In', 'our', 'yellow', 'submarine']
    # tweet10 = ['']
    # tweet11 = ['We', 'all', 'live', 'in', 'a', 'yellow', 'submarine']
    # tweet12 = ['Yellow', 'submarine,', 'yellow', 'submarine']
    # tweet13 = ['We', 'all', 'live', 'in', 'a', 'yellow', 'submarine']
    # tweet14 = ['Yellow', 'submarine,', 'yellow', 'submarine']
    # tweet15 = ['']
    # tweet16 = ['And', 'our', 'friends', 'are', 'all', 'on', 'board']
    # tweet17 = ['...']

    # tweet1 = ['Rag', 'Doll', "livin'", 'in', 'a', 'movie']
    # tweet2 = ['Hot', 'tramp', "Daddy's", 'little', 'cutie']
    # tweet3 = ["You're", 'so', 'fine', "they'll", 'never', 'see', 'ya', "leavin'", 'by', 'the', 'back', 'door,', 'mam']
    # tweet4 = ['Hot', 'time', 'get', 'it', 'while', "it's", 'easy']
    # tweet5 = ["Don't", 'mind', 'come', 'on', 'up', 'and', 'see', 'me']
    # tweet6 = ['Rag', 'Doll', 'baby', "won't", 'you', 'do', 'me', 'like', 'you', 'done', 'before']
    # tweet7 = ['']
    # tweet8 = ["I'm", "feelin'", 'like', 'a', 'bad', 'boy']
    # tweet9 = ['Mm', 'just', 'a', 'like', 'a', 'bad', 'boy']
    # tweet10 = ["I'm", "rippin'", 'up', 'a', 'Rag', 'Doll']
    # tweet11 = ['Like', "throwin'", 'away', 'an', 'old', 'toy']
    # tweet12 = ['Some', "babe's", "talkin'", 'real', 'loud']
    # tweet13 = ["Talkin'", 'all', 'about', 'the', 'new', 'crowd']
    # tweet14 = ['Try', 'and', 'tell', 'me', 'of', 'an', 'old', 'dream']
    # tweet15 = ['A', 'new', 'version', 'of', 'the', 'old', 'scene']
    # tweet16 = ['Speak', 'easy', 'on', 'the', 'grape', 'vine']
    # tweet17 = ['Keep', "shufflin'", 'in', 'a', 'shoe', 'shine']

    # tweet1 = ['You', 'be', 'anything', 'you', 'want']
    # tweet2 = ['Uhh']
    # tweet3 = ['Just', 'keep', 'going,', 'going,', 'gone,', 'gone,', 'gone']
    # tweet4 = ['Uhh']
    # tweet5 = ['It', "don't", 'stop', 'here', 'nigga']
    # tweet6 = ['Yeaah']
    # tweet7 = ['Uhh']
    # tweet8 = ['']
    # tweet9 = ['Back', 'when', 'I', 'was', 'young', 'I', 'had', 'dreams', 'of', 'getting', 'richer']
    # tweet10 = ['Then', 'my', 'homie', 'Breeze', 'set', 'me', 'down', 'schooled', 'me', 'to', 'the', 'picture']
    # tweet11 = ['I', 'was', 'with', 'some', 'wild', 'niggas', 'put', 'me', 'on', 'the', 'game']
    # tweet12 = ['Told', 'me', 'if', 'you', "tryin'", 'to', 'make', 'your', 'move', 'you', 'gotta', 'know', 'your', 'lane', 'homie']
    # tweet13 = ['All', 'you', 'got', 'your', 'name', 'and', 'your', 'words', 'will', 'never', 'break']
    # tweet14 = ['For', 'this', 'life', 'you', 'pay', 'a', 'price', 'you', 'get', 'a', 'chance', 'you', 'gotta', 'take', 'it']
    # tweet15 = ['Cause', 'most', 'niggas', 'never', 'make', 'it', 'they', 'stranded', 'where', "I'm", 'from']
    # tweet16 = ["Ain't", 'no', 'conversation', 'all', 'they', 'understand', 'is', 'get', 'a', 'gun']
    # tweet17 = ['I', 'was', 'riding', 'in', 'my', 'Bona', 'Ville', 'hoping', 'I', 'could', 'make', 'it']

    # tweet1 = ['(Straight', 'up,', 'now', 'tell', 'me', 'do', 'you', 'really', 'wanna', 'love', 'me', 'forever?']
    # tweet2 = ['Oh,', 'oh,', 'oh']
    # tweet3 = ['Or', 'is', 'it', 'just', 'a', 'hit', 'and', 'run?)']
    # tweet4 = ['']
    # tweet5 = ['Hey,', 'we', 'got', 'a', 'good', 'thing']
    # tweet6 = ["Don't", 'know', 'if', 'imma', 'see', 'you', 'again']
    # tweet7 = ['But', 'is', 'that', 'a', 'good', 'thing?']
    # tweet8 = ['Cause', 'girl', 'I', "can't", 'be', 'your', 'man,', 'no', "ma'am"]
    # tweet9 = ['']
    # tweet10 = ['I', 'know', "what's", 'on', 'your', 'brain']
    # tweet11 = ["You're", 'probably', 'hoping', 'it', 'never', 'would', 'end']
    # tweet12 = ['Like', 'is', 'it', 'the', 'real', 'thing']
    # tweet13 = ['Or', 'is', 'it', 'just', 'a', 'one', 'night', 'stand?']
    # tweet14 = ['']
    # tweet15 = ['Let', 'me', 'see', 'you', 'get', 'high', 'and', 'go', 'low']
    # tweet16 = ['Now', 'girl', "won't", 'you', 'drop', 'that', 'thing', 'down', 'to', 'the', 'floor']
    # tweet17 = ["I'm", 'here', 'for', 'one', 'night,', 'how', 'far', 'would', 'you', 'go?']

    # tweet1 = ['Know', "I've", 'done', 'wrong,', 'left', 'your', 'heart', 'torn']
    # tweet2 = ['Is', 'that', 'what', 'devils', 'do?']
    # tweet3 = ['Took', 'you', 'so', 'long,', 'where', 'only', 'fools', 'go']
    # tweet4 = ['I', 'shook', 'the', 'angel', 'in', 'you']
    # tweet5 = ['']
    # tweet6 = ['Now', "I'm", 'rising', 'from', 'the', 'ground']
    # tweet7 = ['Rising', 'up', 'to', 'you']
    # tweet8 = ['Filled', 'with', 'all', 'the', 'strength', "I've", 'found']
    # tweet9 = ["There's", 'nothing', 'I', "can't", 'do']
    # tweet10 = ['']
    # tweet11 = ['I', 'need', 'to', 'know', 'now,', 'know', 'now']
    # tweet12 = ['Can', 'you', 'love', 'me', 'again?']
    # tweet13 = ['I', 'need', 'to', 'know', 'now,', 'know', 'now']
    # tweet14 = ['Can', 'you', 'love', 'me', 'again?']
    # tweet15 = ['I', 'need', 'to', 'know', 'now,', 'know', 'now']
    # tweet16 = ['Can', 'you', 'love', 'me', 'again?']
    # tweet17 = ['I', 'need', 'to', 'know', 'now,', 'know', 'now']

    # tweet1 = ['Come', 'on,', 'come', 'on']
    # tweet2 = ['I', 'see', 'no', 'changes,', 'wake', 'up', 'in', 'the', 'morning', 'and', 'I', 'ask', 'myself']
    # tweet3 = ['Is', 'life', 'worth', 'living,', 'should', 'I', 'blast', 'myself?']
    # tweet4 = ["I'm", 'tired', 'of', "bein'", 'poor', 'and', 'even', 'worse', "I'm", 'black']
    # tweet5 = ['My', 'stomach', 'hurts,', 'so', "I'm", "lookin'", 'for', 'a', 'purse', 'to', 'snatch']
    # tweet6 = ['']
    # tweet7 = ['Cops', 'give', 'a', 'damn', 'about', 'a', 'negro']
    # tweet8 = ['Pull', 'the', 'trigger,', 'kill', 'a', 'n**ga,', "he's", 'a', 'hero']
    # tweet9 = ['Give', 'the', 'crack', 'to', 'the', 'kids', 'who', 'the', 'hell', 'cares']
    # tweet10 = ['One', 'less', 'hungry', 'mouth', 'on', 'the', 'welfare']
    # tweet11 = ['']
    # tweet12 = ['First', 'ship', "'em", 'dope', 'and', 'let', "'em", 'deal', 'the', 'brothers']
    # tweet13 = ['Give', "'em", 'guns,', 'step', 'back,', 'watch', "'em", 'kill', 'each', 'other']
    # tweet14 = ["It's", 'time', 'to', 'fight', 'back', "that's", 'what', 'Huey', 'said']
    # tweet15 = ['Two', 'shots', 'in', 'the', 'dark,', 'now', "Huey's", 'dead']
    # tweet16 = ['']
    # tweet17 = ['I', 'got', 'love', 'for', 'my', 'brother', 'but', 'we', 'can', 'never', 'go', 'nowhere']

    # tweet1 = ['I', 'usually', 'love', 'sleeping', 'all', 'alone']
    # tweet2 = ['This', 'time', 'around', 'bring', 'your', 'friend', 'with', 'you']
    # tweet3 = ['But', 'we', "ain't", 'really', 'going', 'to', 'sleep', 'at', 'all']
    # tweet4 = ['You', "ain't", 'gonna', 'catch', 'me', 'with', 'them', 'sneak', 'pictures']
    # tweet5 = ['In', 'my', 'city', "I'm", 'a', 'young', 'god']
    # tweet6 = ['That', 'pussy', 'kill', 'be', 'so', 'vicious']
    # tweet7 = ['My', 'god', 'white,', 'he', 'in', 'my', 'pocket']
    # tweet8 = ['Get', 'me', 'redder', 'than', 'the', 'devil', "'til", 'I', 'go', 'nauseous']
    # tweet9 = ['']
    # tweet10 = ['Ask', 'me', 'if', 'I', 'do', 'this', 'every', 'day,', 'I', 'said', '"Often"']
    # tweet11 = ['Ask', 'how', 'many', 'times', 'she', 'rode', 'the', 'wave,', '"Not', 'so', 'often"']
    # tweet12 = ['Bitches', 'down', 'to', 'do', 'it', 'either', 'way,', 'often']
    # tweet13 = ['Baby', 'I', 'can', 'make', 'that', 'pussy', 'rain,', 'often']
    # tweet14 = ['Often,', 'often,', 'girl', 'I', 'do', 'this', 'often']
    # tweet15 = ['Make', 'that', 'pussy', "poppin',", 'do', 'it', 'how', 'I', 'want', 'it']
    # tweet16 = ['Often,', 'often,', 'girl', 'I', 'do', 'this', 'often']
    # tweet17 = ['Make', 'that', 'pussy', "poppin',", 'do', 'it', 'how', 'I', 'want', 'it']

    # tweet1 = ['Check', 'me', 'out', "y'all"]
    # tweet2 = ['Nasty', 'Nas', 'in', 'your', 'area']
    # tweet3 = ['About', 'to', 'cause', 'mass', 'hysteria']
    # tweet4 = ['']
    # tweet5 = ['Before', 'I', 'blunt,', 'I', 'take', 'out', 'my', 'fronts']
    # tweet6 = ['Then', 'I', 'start', 'to', 'front;', 'matter', 'of', 'fact,', 'I', 'be', 'on', 'a', 'manhunt']
    # tweet7 = ['You', "couldn't", 'catch', 'me', 'in', 'the', 'streets', 'without', 'a', 'ton', 'of', 'reefer']
    # tweet8 = ["That's", 'like', 'Malcolm', 'X', 'catching', 'the', 'Jungle', 'Fever']
    # tweet9 = ['King', 'poetic.', 'Too', 'much', 'flavor,', "I'm", 'major']
    # tweet10 = ['Atlanta', "ain't", 'Brave-r,', "I'll", 'pull', 'a', 'number', 'like', 'a', 'pager']
    # tweet11 = ['Cause', "I'm", 'an', 'ace', 'when', 'I', 'face', 'the', 'bass']
    # tweet12 = ['40-side', 'is', 'the', 'place', 'that', 'is', 'giving', 'me', 'grace']
    # tweet13 = ['Now', 'wait,', 'another', 'dose', 'and', 'you', 'might', 'be', 'dead']
    # tweet14 = ['And', "I'm", 'a', 'Nike-head,', 'I', 'wear', 'chains', 'that', 'excite', 'the', 'Feds']
    # tweet15 = ['And', "ain't", 'a', 'damn', 'thing', 'gonna', 'change']
    # tweet16 = ["I'mma", 'performer', 'strange,', 'so', 'the', 'mic', 'warmer', 'was', 'born', 'to', 'gain']
    # tweet17 = ['Nas,', 'why', 'did', 'you', 'do', 'it']

    # tweet1 = ['Baby,', "I'm", 'preying', 'on', 'you', 'tonight']
    # tweet2 = ['Hunt', 'you', 'down', 'eat', 'you', 'alive']
    # tweet3 = ['Just', 'like', 'animals']
    # tweet4 = ['Animals']
    # tweet5 = ['Like', 'animals']
    # tweet6 = ['']
    # tweet7 = ['Maybe', 'you', 'think', 'that', 'you', 'can', 'hide']
    # tweet8 = ['I', 'can', 'smell', 'your', 'scent', 'for', 'miles']
    # tweet9 = ['Just', 'like', 'animals']
    # tweet10 = ['Animals']
    # tweet11 = ['Like', 'animals']
    # tweet12 = ['Baby,', "I'm"]
    # tweet13 = ['']
    # tweet14 = ['So', 'what', 'you', 'trying', 'to', 'do', 'to', 'me']
    # tweet15 = ["It's", 'like', 'we', "can't", 'stop', "we're", 'enemies']
    # tweet16 = ['But', 'we', 'get', 'along', 'when', "I'm", 'inside', 'you']
    # tweet17 = ["You're", 'like', 'a', 'drug', "that's", 'killing', 'me']

    # tweet1 = ['It', 'might', 'seem', 'crazy', 'what', 'I', 'am', 'about', 'to', 'say']
    # tweet2 = ['Sunshine', "she's", 'here,', 'you', 'can', 'take', 'a', 'break']
    # tweet3 = ["I'm", 'a', 'hot', 'air', 'balloon', 'that', 'could', 'go', 'to', 'space']
    # tweet4 = ['With', 'the', 'air,', 'like', 'I', "don't", 'care', 'baby', 'by', 'the', 'way']
    # tweet5 = ['']
    # tweet6 = ['Because', "I'm", 'happy']
    # tweet7 = ['Clap', 'along', 'if', 'you', 'feel', 'like', 'a', 'room', 'without', 'a', 'roof']
    # tweet8 = ['Because', "I'm", 'happy']
    # tweet9 = ['Clap', 'along', 'if', 'you', 'feel', 'like', 'happiness', 'is', 'the', 'truth']
    # tweet10 = ['Because', "I'm", 'happy']
    # tweet11 = ['Clap', 'along', 'if', 'you', 'know', 'what', 'happiness', 'is', 'to', 'you']
    # tweet12 = ['Because', "I'm", 'happy']
    # tweet13 = ['Clap', 'along', 'if', 'you', 'feel', 'like', "that's", 'what', 'you', 'wanna', 'do']
    # tweet14 = ['']
    # tweet15 = ['Here', 'come', 'bad', 'news', 'talking', 'this', 'and', 'that']
    # tweet16 = ['Yeah,', 'give', 'me', 'all', 'you', 'got,', "don't", 'hold', 'back']
    # tweet17 = ['Yeah,', 'well', 'I', 'should', 'probably', 'warn', 'you', "I'll", 'be', 'just', 'fine']

    # tweet1 = ['Had', 'hit', 'records', 'on', 'my', 'demo']
    # tweet2 = ['Did', "y'all", 'boys', 'not', 'get', 'the', 'memo']
    # tweet3 = ['I', 'do', 'not', 'stay', 'at', 'the', 'Intercontinental']
    # tweet4 = ['And', 'anything', 'I', 'got', 'is', 'not', 'a', 'rental,', 'I', 'own', 'that', 'mothafucka']
    # tweet5 = ['Figured', 'out', 'this', 'shit,', "it's", 'simple']
    # tweet6 = ['My', 'stock', 'been', 'going', 'up', 'like', 'a', 'crescendo']
    # tweet7 = ['A', 'bunch', 'of', 'handshakes', 'from', 'the', 'fakes']
    # tweet8 = ['But', 'nigga', 'I', 'do', 'not', 'want', 'to', 'be', 'friends', 'though']
    # tweet9 = ['I', 'told', "y'all", 'mafuckas,', 'man,', 'this', 'shit', 'is', 'not', 'a', 'love', 'song']
    # tweet10 = ['This', 'is', 'a', 'fuck', 'a', 'stripper', 'on', 'a', 'mink', 'rug', 'song']
    # tweet11 = ['This', 'a', 'fuck', 'them', 'boys', 'forever,', 'hold', 'a', 'grudge', 'song']
    # tweet12 = ['Pop', 'some', 'fucking', 'champagne', 'in', 'the', 'tub', 'song,', 'nigga,', '"just', 'because"', 'song']
    # tweet13 = ['']
    # tweet14 = ["What's", 'the', 'move?', 'Can', 'I', 'tell', 'truth?']
    # tweet15 = ['If', 'I', 'was', 'doing', 'this', 'for', 'you']
    # tweet16 = ['Then', 'I', 'have', 'nothing', 'left', 'to', 'prove,', 'nah']
    # tweet17 = ['...']

    # tweet1 = ['Me', 'and', 'my', 'niggas', 'tryna', 'get', 'it,', 'ya', 'bish']
    # tweet2 = ['Hit', 'this', 'house', 'lick', 'tell', 'me', 'is', 'you', 'with', 'it,', 'ya', 'bish']
    # tweet3 = ['Home', 'invasion', 'was', 'persuasive']
    # tweet4 = ['From', 'nine', 'to', 'five', 'I', 'know', 'its', 'vacant,', 'ya', 'bish']
    # tweet5 = ['Dreams', 'of', 'living', 'life', 'like', 'rappers', 'do']
    # tweet6 = ['Back', 'when', 'condom', 'wrappers', "wasn't", 'cool']
    # tweet7 = ['I', 'fucked', 'Sherene', 'then', 'went', 'to', 'tell', 'my', 'bros']
    # tweet8 = ['Then', 'Usher', 'Raymond', '"Let', 'it', 'Burn"', 'came', 'on']
    # tweet9 = ['Hot', 'sauce', 'all', 'in', 'our', 'Top', 'Ramen,', 'ya', 'bish']
    # tweet10 = ['Parked', 'the', 'car', 'and', 'then', 'we', 'start', 'rhyming,', 'ya', 'bish']
    # tweet11 = ['The', 'only', 'thing', 'we', 'had', 'to', 'free', 'our', 'mind']
    # tweet12 = ['Then', 'freeze', 'that', 'verse', 'when', 'we', 'see', 'dollar', 'signs']
    # tweet13 = ['You', 'looking', 'like', 'an', 'easy', 'come', 'up,', 'ya', 'bish']
    # tweet14 = ['A', 'silver', 'spoon', 'I', 'know', 'you', 'come', 'from,', 'ya', 'bish']
    # tweet15 = ['And', "that's", 'a', 'lifestyle', 'that', 'we', 'never', 'knew']
    # tweet16 = ['Go', 'at', 'a', 'reverend', 'for', 'the', 'revenue']
    # tweet17 = ['']

    # tweet1 = ['Yeah!', 'When', "I'm", 'out', 'in', 'N.Y.', 'boy', "it's", 'blunts', 'and', 'Phillies']
    # tweet2 = ['When', "I'm", 'out', 'in', 'L.A.', 'boy', "it's", 'wraps', 'and', 'swishes']
    # tweet3 = ['Now', 'Blood', 'walk', 'to', 'this,', 'now', 'Crips', 'walk', 'to', 'this']
    # tweet4 = ['Now', 'throw', 'it', 'up,', 'raise', 'it', 'up', 'for', 'that', 'gangster', 'shit']
    # tweet5 = ['Now', 'Blood', 'walk', 'to', 'this,', 'now', 'Crips', 'walk', 'to', 'this']
    # tweet6 = ['Now', 'throw', 'it', 'up,', 'raise', 'it', 'up', 'for', 'that', 'gangster', 'shit']
    # tweet7 = ['']
    # tweet8 = ['Im', 'in', 'my', 'lambo', 'maggot']
    # tweet9 = ['my', 'fo', 'fo', 'fagget']
    # tweet10 = ['doors', 'cliffed', 'up', 'im', 'like', 'go', 'go', 'gadget']
    # tweet11 = ['see', 'this', 'shit', 'I', 'got', 'on']
    # tweet12 = ['homie', "i'd", 'hate', 'to']
    # tweet13 = ['my', 'teflon', 'on', 'boy', 'my', 'goverment', 'issue']
    # tweet14 = ['I', 'hit', 'your', 'vertebrate,', 'bullet', 'went', 'through', 'tissue']
    # tweet15 = ['your', 'wife', 'on', 'the', 'futon', 'huggin', 'her', 'shit', 'soon']
    # tweet16 = ['homie', 'you', 'a', 'bitch', 'you', 'got', 'feminime', 'ways']
    # tweet17 = ['heard', 'you', 'got', 'four', 'lips', 'and', 'bleed', 'for', 'seven', 'days']

    # tweet1 = ['Walk', 'a', 'mile', 'in', 'my', 'Chucks,', 'see', 'where', 'you', 'end', 'up']
    # tweet2 = ['You', 'can', 'tell', "'em", 'that']
    # tweet3 = ["I've", 'been', 'through', 'hell', 'and', 'back']
    # tweet4 = ['']
    # tweet5 = ['You', 'can', 'tell', "'em", 'that']
    # tweet6 = ["I've", 'been', 'from', 'hell', 'and', 'back']
    # tweet7 = ['When', 'the', 'heat', 'is', 'on,', 'I', 'fire', 'back']
    # tweet8 = ['In', 'this', 'cold', 'world,', 'where', 'your', 'lighters', 'at']
    # tweet9 = ["Let's", 'burn', 'it', 'down,', 'f-f-fire', 'back']
    # tweet10 = ['']
    # tweet11 = ['Uh,', "let's", 'burn', 'it', 'down,', 'underrated']
    # tweet12 = ['Could', 'never', 'say', 'I', 'was', 'underground']
    # tweet13 = ['Maybe', 'a', 'little', 'misunderstood', 'when', "I'm", 'just', 'riding', 'round']
    # tweet14 = ['']
    # tweet15 = ['In', 'all', 'lanes,', 'like', 'OJ']
    # tweet16 = ['Doing', 'big', 'things,', 'no', 'small', 'change']
    # tweet17 = ['We', "ain't", 'going', 'nowhere', 'like', 'wine', 'stains']

    # tweet1 = ["I'm", 'rolling', 'thunder', 'pouring', 'rain']
    # tweet2 = ["I'm", 'coming', 'on', 'like', 'a', 'hurricane']
    # tweet3 = ['My', "lightning's", 'flashing', 'across', 'the', 'sky']
    # tweet4 = ["You're", 'only', 'young', 'but', "you're", 'gonna', 'die']
    # tweet5 = ['I', "won't", 'take', 'no', 'prisoners', "won't", 'spare', 'no', 'lives']
    # tweet6 = ["Nobody's", 'putting', 'up', 'a', 'fight']
    # tweet7 = ['I', 'got', 'my', 'bell', "I'm", 'gonna', 'take', 'you', 'to', 'hell']
    # tweet8 = ["I'm", 'gonna', 'get', 'ya', 'satan', 'get', 'ya']
    # tweet9 = ['']
    # tweet10 = ['Hells', 'bells']
    # tweet11 = ['Hells', 'bells,', 'you', 'got', 'me', 'ringing']
    # tweet12 = ['Hells', 'bells,', 'my', "temperature's", 'high']
    # tweet13 = ['Hells', 'bells']
    # tweet14 = ['...']
    # tweet15 = ['']
    # tweet16 = ['...']
    # tweet17 = ['']

    # tweet1 = ['Baby,', 'are', 'you', 'down,', 'down,', 'down,', 'down,', 'down?']
    # tweet2 = ['Down,', 'down']
    # tweet3 = ['Even', 'if', 'the', 'sky', 'is', 'falling', 'down?']
    # tweet4 = ['Down,', 'down']
    # tweet5 = ['']
    # tweet6 = ['You', 'oughta', 'know']
    # tweet7 = ['Tonight', 'is', 'the', 'night', 'to', 'let', 'it', 'go']
    # tweet8 = ['Put', 'on', 'a', 'show']
    # tweet9 = ['I', 'wanna', 'see', 'how', 'you', 'lose', 'control']
    # tweet10 = ['']
    # tweet11 = ['So', 'leave', 'it', 'behind']
    # tweet12 = ["'Cause", 'we', 'have', 'a', 'night', 'to', 'get', 'away']
    # tweet13 = ['So', 'come', 'on', 'and', 'fly', 'with', 'me']
    # tweet14 = ['As', 'we', 'make', 'our', 'great', 'escape']
    # tweet15 = ['']
    # tweet16 = ['So', 'baby,', "don't", 'worry']
    # tweet17 = ['You', 'are', 'my', 'only']

    # tweet1 = ["You'll", 'never', 'make', 'me', 'stay']
    # tweet2 = ['So', 'take', 'your', 'weight', 'off', 'me']
    # tweet3 = ['I', 'know', 'your', 'every', 'move']
    # tweet4 = ['']
    # tweet5 = ['So', "won't", 'you', 'just', 'let', 'me', 'be']
    # tweet6 = ["I've", 'been', 'here', 'times', 'before']
    # tweet7 = ['But', 'I', 'was', 'too', 'blind', 'to', 'see']
    # tweet8 = ['That', 'you', 'seduce', 'every', 'men']
    # tweet9 = ['This', 'time', 'you', "won't", 'seduce', 'me']
    # tweet10 = ["She's", 'saying', "that's", 'ok']
    # tweet11 = ['Hey', 'baby', 'do', 'what', 'you', 'please']
    # tweet12 = ['I', 'have', 'the', 'stuff', 'that', 'you', 'want']
    # tweet13 = ['']
    # tweet14 = ['I', 'am', 'the', 'thing', 'that', 'you', 'need']
    # tweet15 = ['She', 'looked', 'me', 'deep', 'in', 'the', 'eyes']
    # tweet16 = ["She's", 'touchin', 'me', 'so', 'to', 'start']
    # tweet17 = ['She', 'says', "there's", 'no', 'turnin', 'back']

    # tweet1 = ['I', 'walk', 'a', 'lonely', 'road']
    # tweet2 = ['The', 'only', 'one', 'that', 'I', 'have', 'ever', 'known']
    # tweet3 = ["Don't", 'know', 'where', 'it', 'goes']
    # tweet4 = ['But', "it's", 'home', 'to', 'me', 'and', 'I', 'walk', 'alone']
    # tweet5 = ['']
    # tweet6 = ['I', 'walk', 'this', 'empty', 'street']
    # tweet7 = ['On', 'the', 'Boulevard', 'of', 'Broken', 'Dreams']
    # tweet8 = ['Where', 'the', 'city', 'sleeps']
    # tweet9 = ['and', "I'm", 'the', 'only', 'one', 'and', 'I', 'walk', 'alone']
    # tweet10 = ['']
    # tweet11 = ['I', 'walk', 'alone']
    # tweet12 = ['I', 'walk', 'alone']
    # tweet13 = ['I', 'walk', 'alone']
    # tweet14 = ['I', 'walk', 'a...']
    # tweet15 = ['']
    # tweet16 = ['My', "shadow's", 'the', 'only', 'one', 'that', 'walks', 'beside', 'me']
    # tweet17 = ['My', 'shallow', "heart's", 'the', 'only', 'thing', "that's", 'beating']

    # tweet1 =['You ', 'already', ' know', ' who', ' it', 'is']
    # tweet2 =['Silento']
    # tweet3 =['Silento']
    # tweet4 =['Gonna', 'do',' it',' for',' you']
    # tweet5 =['Now ','watch ','me ','whip']
    # tweet6 =['Now ','watch',' me ','nae ','nae']
    # tweet7 =['Now ','watch',' me ','whip ','whip']
    # tweet8 =['Watch',' me ','nae ','nae']
    # tweet9 =['Now ','watch',' me ','whip',' Kill ','it']
    # tweet10 =['Watch ','me ','nae',' nae',' Okay']
    # tweet11 =['Now',' watch',' me ','whip ','whip']

    # tweet12 =['Watch',' me ','nae',' nae']
    # tweet13 =['Now',' watch ','me']
    # tweet13 = ['Ooh',' watch',' me',' watch',' me']
    # tweet14 = ['Ooh',' watch',' me',' watch',' me']
    # tweet15 = ['Ooh',' watch',' me',' watch',' me']
    # tweet16 =['Ooh',' ooh',' ooh',' ooh']
    # tweet17 =['Ooh',' ooh',' ooh',' ooh']

    # tweet1 = ['Well ','you ','can',' tell ','by',' the',' way ','I ','use ','my',' walk']
    # tweet2 = [' Im',' a ','womans ','man',' no',' time ','to',' talk']
    # tweet3 = ['Music ','loud',' and',' women',' warm.']
    # tweet4 = ['Ive ','been ','kicked ','around ','since',' I ','was',' born']
    # tweet5 = ['And ','now',' its ','all',' right',' its ','okay']
    # tweet6 = ['And',' you',' may',' look ','the ','other',' way']
    # tweet7 = ['We ','can ','try',' to',' understand']
    # tweet8 = ['The ','New ','York',' Times ','effect',' on ','man']
    # tweet9 = ['Whether',' youre ','a','',' brother']
    # tweet10 = ['Or ','whether ','youre',' a ','mother']
    # tweet11 = ['Youre ','stayin',' alive',' stayin ','alive']
    # tweet12 = ['Feel',' the',' city ','breakin']
    # tweet13 = ['And ','everybody',' shakin']
    # tweet14 = ['And ','were',' stayin ','alive ','stayin',' alive']
    # tweet15 = ['Ah',' ha',' ha',' ha']
    # tweet16 = ['Stayin ','alive']
    # tweet17 = ['Stayin ','alive']

    # tweet1 = [' Buffalo',' soldier',' dreadlock',' rasta']
    # tweet2 = ['There ','was ','a ','buffalo ','soldier',' in ','the ','heart ','of',' America']
    # tweet3 = ['Stolen ','from ','Africa ','brought ','to',' America']
    # tweet4 = ['Fighting',' on ','arrival ','fighting',' for ','survival']

    # tweet5 = ['I ','mean',' it ','when',' I ','analyze',' the',' stench']
    # tweet6 = ['To ','me ','it ','makes ','a',' lot ','of',' sense']
    # tweet7 = ['How ','the ','dreadlock',' rasta ','was ','the',' buffalo ','soldier']
    # tweet8 = ['And ','he',' was ','taken ','from ','Africa',' brought ','to ','America']
    # tweet9 = ['Fighting ','on ','arrival ','fighting',' for',' survival']

    # tweet10 = ['Said ','he',' was',' a ','buffalo',' soldier ','dreadlock ','rasta']
    # tweet11 = ['Buffalo',' soldier',' in',' the',' heart',' of',' America']

    # tweet12 = ['If ','you ','know',' your',' history']
    # tweet13 = ['Then',' you ','would ','know',' where ','youre ','coming ','from']
    # tweet14 = ['Then ','you ','wouldnt ','have ','to ','ask ','me']
    # tweet15 = ['I ','mean',' it ','when',' I ','analyze',' the',' stench']
    # tweet16 = ['To ','me ','it ','makes ','a',' lot ','of',' sense']
    # tweet17 = ['How ','the ','dreadlock',' rasta ','was ','the',' buffalo ','soldier']

    # tweet1 = ['I', 'know', 'you', "don't", 'get', 'chance', 'to', 'take', 'a', 'break', 'this', 'often']
    # tweet2 = ['I', 'know', 'your', 'life', 'is', 'speeding', 'and', 'it', "isn't", 'stopping']
    # tweet3 = ['You', 'take', 'my', 'shirt', 'and', 'just', 'go', 'ahead', 'and', 'wipe', 'up', 'all', 'the']
    # tweet4 = ['Sweat,', 'sweat,', 'sweat']
    # tweet5 = ['Sweat,', 'sweat,', 'sweat']
    # tweet6 = ['Lose', 'yourself', 'to', 'dance']
    # tweet7 = ['Lose', 'yourself', 'to', 'dance']
    # tweet8 = ['Lose', 'yourself', 'to', 'dance']
    # tweet9 = ['Lose', 'yourself', 'to', 'dance']
    # tweet10 = ['Lose', 'yourself', 'to', 'dance']
    # tweet11 = ['Lose', 'yourself', 'to', 'dance']
    # tweet12 = ['Lose', 'yourself', 'to', 'dance']
    # tweet13 = ['Lose', 'yourself', 'to', 'dance']
    # tweet14 = ['Lose', 'yourself', 'to', 'dance']
    # tweet15 = ['Sweat,', 'sweat,', 'sweat']
    # tweet16 = ['I', 'know', 'you', "don't", 'get', 'chance', 'to', 'take', 'a', 'break', 'this', 'often']
    # tweet17 = ['I', 'know', 'your', 'life', 'is', 'speeding', 'and', 'it', "isn't", 'stopping']

    # tweet1 = ['You', 'would', 'not', 'believe', 'your', 'eyes']
    # tweet2 = ['If', 'ten', 'million', 'fireflies']
    # tweet3 = ['Lit', 'up', 'the', 'world', 'as', 'I', 'fell', 'asleep']
    # tweet4 = ["'Cause", "they'd", 'fill', 'the', 'open', 'air']
    # tweet5 = ['And', 'leave', 'teardrops', 'everywhere']
    # tweet6 = ["You'd", 'think', 'me', 'rude']
    # tweet7 = ['But', 'I', 'would', 'just', 'stand', 'and', 'stare']
    # tweet8 = ['From', 'ten', 'thousand', 'lightning', 'bugs']
    # tweet9 = ["I'd", 'like', 'to', 'make', 'myself', 'believe']
    # tweet10 = ['That', 'planet', 'Earth', 'turns', 'slowly']
    # tweet11 = ["It's", 'hard', 'to', 'say', 'that', "I'd", 'rather', 'stay']
    # tweet12 = ['Awake', 'when', "I'm", 'asleep']
    # tweet13 = ['As', 'they', 'tried', 'to', 'teach', 'me', 'how', 'to', 'dance']
    # tweet14 = ["'Cause", 'everything', 'is', 'never', 'as', 'it', 'seems']
    # tweet15 = ["'Cause", "I'd", 'get', 'a', 'thousand', 'hugs']
    # tweet16 = ['From', 'ten', 'thousand', 'lightning', 'bugs']
    # tweet17 = ['As', 'they', 'tried', 'to', 'teach', 'me', 'how', 'to', 'dance']

    # tweet1 = ['When', 'the', 'days', 'are', 'cold']
    # tweet2 = ['And', 'the', 'cards', 'all', 'fold']
    # tweet3 = ['And', 'the', 'saints', 'we', 'see']
    # tweet4 = ['Are', 'all', 'made', 'of', 'gold']
    # tweet5 = ['']
    # tweet6 = ['When', 'your', 'dreams', 'all', 'fail']
    # tweet7 = ['And', 'the', 'ones', 'we', 'hail']
    # tweet8 = ['Are', 'the', 'worst', 'of', 'all']
    # tweet9 = ['And', 'the', "blood's", 'run', 'stale']
    # tweet10 = ['']
    # tweet11 = ['I', 'wanna', 'hide', 'the', 'truth']
    # tweet12 = ['I', 'wanna', 'shelter', 'you']
    # tweet13 = ['But', 'with', 'the', 'beast', 'inside']
    # tweet14 = ["There's", 'nowhere', 'we', 'can', 'hide']
    # tweet15 = ['']
    # tweet16 = ['No', 'matter', 'what', 'we', 'breed']
    # tweet17 = ['We', 'still', 'are', 'made', 'of', 'greed']

    # tweet1 = ['Bed,', 'stay', 'in', 'bed,']
    # tweet2 = ['The', 'feeling', 'of', 'your', 'skin', 'locked', 'in', 'my', 'head']
    # tweet3 = ['Smoke', 'smoke', 'me', 'broke']
    # tweet4 = ['I', "don't", 'care,', "I'm", 'down', 'for', 'what', 'you', 'want']
    # tweet5 = ['Day', 'drunk', 'into', 'the', 'night,', 'wanna', 'keep', 'you', 'here']
    # tweet6 = ["'Cause", 'you', 'dry', 'my', 'tears']
    # tweet7 = ['Yeah,', 'summer', 'loving', 'and', 'fights']
    # tweet8 = ['How', 'it', 'is', 'for', 'us,', 'and', "it's", 'all', 'because']
    # tweet9 = ['']
    # tweet10 = ['Now', 'if', "we're", 'talking', 'body']
    # tweet11 = ["You've", 'got', 'a', 'perfect', 'one,', 'so', 'put', 'it', 'on', 'me']
    # tweet12 = ['Swear', 'it', "won't", 'take', 'you', 'long']
    # tweet13 = ['If', 'you', 'love', 'me', 'right']
    # tweet14 = ['We', 'fuck', 'for', 'life,', 'on', 'and', 'on', 'and', 'on']
    # tweet15 = ['Now', 'if', "we're", 'talking', 'body']
    # tweet16 = ["You've", 'got', 'a', 'perfect', 'one,', 'so', 'put', 'it', 'on', 'me']
    # tweet17 = ['Swear', 'it', "won't", 'take', 'you', 'long']

    # tweet1 = ['I', 'could', 'lift', 'you', 'up']
    # tweet2 = ['I', 'could', 'show', 'you', 'what', 'you', 'wanna', 'see']
    # tweet3 = ['and', 'take', 'you', 'where', 'you', 'wannna', 'be']
    # tweet4 = ['']
    # tweet5 = ['You', 'could', 'be', 'my', 'luck']
    # tweet6 = ['Even', 'if', 'the', 'sky', 'is', 'falling', 'down']
    # tweet7 = ['I', 'know', 'that', "we'll", 'be', 'safe', 'and', 'sound']
    # tweet8 = ['We', 'safe', 'and', 'sound']
    # tweet9 = ['']
    # tweet10 = ['I', 'could', 'fill', 'your', 'cup']
    # tweet11 = ['You', 'know', 'my', 'river', "won't", 'evaporate']
    # tweet12 = ['This', 'world', 'we', 'still', 'appreciate']
    # tweet13 = ['You', 'could', 'be', 'my', 'luck']
    # tweet14 = ['Even', 'in', 'a', 'hurricane', 'of', 'frowns']
    # tweet15 = ['I', 'know', 'that', "we'll", 'be', 'safe', 'and', 'sound']
    # tweet16 = ['We', 'safe', 'and', 'sound']
    # tweet17 = ['We', 'safe', 'and', 'sound']

    # tweet1 = ["Gettin'", 'born', 'in', 'the', 'state', 'of', 'Mississippi']
    # tweet2 = ['Papa', 'was', 'a', 'copper', 'and', 'mama', 'was', 'a', 'hippie']
    # tweet3 = ['In', 'Alabama', 'she', 'would', 'swing', 'a', 'hammer']
    # tweet4 = ['Price', 'you', 'gotta', 'pay', 'when', 'you', 'pick', 'the', 'panorama']
    # tweet5 = ['She', 'never', 'knew', 'that', 'there', 'was', 'anything', 'more', 'than', 'poor']
    # tweet6 = ['What', 'in', 'the', 'world?', 'What', 'does', 'your', 'company', 'take', 'me', 'for?']
    # tweet7 = ['']
    # tweet8 = ['Black', 'bandana,', 'sweet', 'Louisiana']
    # tweet9 = ["Robbin'", 'on', 'a', 'bank', 'in', 'the', 'state', 'of', 'Indiana']
    # tweet10 = ["She's", 'a', 'runner,', 'rebel', 'and', 'a', 'stunner']
    # tweet11 = ['Oh', 'her', 'merry', 'way', "sayin'", 'baby', 'whatcha', 'gonna']
    # tweet12 = ["Lookin'", 'down', 'the', 'barrel', 'of', 'a', 'hot', 'metal', 'forty-five']
    # tweet13 = ['Just', 'another', 'way', 'to', 'survive']
    # tweet14 = ['']
    # tweet15 = ['California,', 'rest', 'in', 'peace']
    # tweet16 = ['Simultaneous', 'release']
    # tweet17 = ['California,', 'show', 'your', 'teeth']

    # tweet1 = ['The', 'snow', 'glows', 'white', 'on', 'the', 'mountain', 'tonight']
    # tweet2 = ['Not', 'a', 'footprint', 'to', 'be', 'seen']
    # tweet3 = ['A', 'kingdom', 'of', 'isolation']
    # tweet4 = ['and', 'it', 'looks', 'like', "I'm", 'the', 'queen']
    # tweet5 = ['']
    # tweet6 = ['The', 'wind', 'is', 'howling', 'like', 'this', 'swirling', 'storm', 'inside']
    # tweet7 = ["Couldn't", 'keep', 'it', 'in,', 'Heaven', 'knows', "I've", 'tried']
    # tweet8 = ['']
    # tweet9 = ["Don't", 'let', 'them', 'in,', "don't", 'let', 'them', 'see']
    # tweet10 = ['Be', 'the', 'good', 'girl', 'you', 'always', 'have', 'to', 'be']
    # tweet11 = ['Conceal,', "don't", 'feel,', "don't", 'let', 'them', 'know']
    # tweet12 = ['Well,', 'now', 'they', 'know']
    # tweet13 = ['']
    # tweet14 = ['Let', 'it', 'go,', 'let', 'it', 'go']
    # tweet15 = ["Can't", 'hold', 'it', 'back', 'anymore']
    # tweet16 = ['Let', 'it', 'go,', 'let', 'it', 'go']
    # tweet17 = ['...']

    # tweet1 = ['This', 'hit,', 'that', 'ice', 'cold']
    # tweet2 = ['Michelle', 'Pfeiffer,', 'that', 'white', 'gold']
    # tweet3 = ['This', 'one', 'for', 'them', 'hood', 'girls']
    # tweet4 = ['Them', 'good', 'girls', 'straight', 'masterpieces']
    # tweet5 = ["Stylin',", 'whilen']
    # tweet6 = ["Livin'", 'it', 'up', 'in', 'the', 'city']
    # tweet7 = ['Got', 'Chucks', 'on', 'with', 'Saint', 'Laurent']
    # tweet8 = ['Got', 'kiss', 'myself,', "I'm", 'so', 'pretty']
    # tweet9 = ['']
    # tweet10 = ["I'm", 'too', 'hot', '(hot', 'damn)']
    # tweet11 = ['Called', 'a', 'police', 'and', 'a', 'fireman']
    # tweet12 = ["I'm", 'too', 'hot', '(hot', 'damn)']
    # tweet13 = ['Make', 'a', 'dragon', 'wanna', 'retire', 'man']
    # tweet14 = ["I'm", 'too', 'hot', '(hot', 'damn)']
    # tweet15 = ['Say', 'my', 'name', 'you', 'know', 'who', 'I', 'am']
    # tweet16 = ["I'm", 'too', 'hot', '(hot', 'damn)']
    # tweet17 = ['Am', 'I', 'bad', "'bout", 'that', 'money']


    # tweet1 = ['Who', 'am', 'I,', 'that', 'the', 'Lord', 'of', 'all', 'the', 'earth']
    # tweet2 = ['Would', 'care', 'to', 'know', 'my', 'name']
    # tweet3 = ['Would', 'care', 'to', 'feel', 'my', 'hurt?']
    # tweet4 = ['Who', 'am', 'I,', 'that', 'the', 'bright', 'and', 'morning', 'star']
    # tweet5 = ['Would', 'choose', 'to', 'light', 'the', 'way']
    # tweet6 = ['For', 'my', 'ever', 'wondering', 'heart?']
    # tweet7 = ['']
    # tweet8 = ['Not', 'because', 'of', 'who', 'I', 'am']
    # tweet9 = ['But', 'because', 'of', 'what', "You've", 'done']
    # tweet10 = ['Not', 'because', 'of', 'what', "I've", 'done']
    # tweet11 = ['But', 'because', 'of', 'who', 'You', 'are']
    # tweet12 = ['']
    # tweet13 = ['I', 'am', 'a', 'flower', 'quickly', 'fading']
    # tweet14 = ['Here', 'today', 'and', 'gone', 'tomorrow']
    # tweet15 = ['A', 'wave', 'tossed', 'in', 'the', 'ocean']
    # tweet16 = ['A', 'vapor', 'in', 'the', 'wind']
    # tweet17 = ['Still', 'You', 'hear', 'me', 'when', "I'm", 'calling']

    # tweet1 = ['Somewhere', 'between', 'psychotic', 'and', 'iconic']
    # tweet2 = ['Somewhere', 'between', 'I', 'want', 'it', 'and', 'I', 'got', 'it']
    # tweet3 = ['Somewhere', 'between', "I'm", 'sober', 'and', "I'm", 'lifted']
    # tweet4 = ['Somewhere', 'a', 'mistress', 'and', 'commitment']
    # tweet5 = ['But', 'I', 'stay', 'down,', 'girl,', 'I', 'always', 'stay', 'down']
    # tweet6 = ['Get', 'down,', 'have', 'her', 'lay', 'down']
    # tweet7 = ['Promise', 'to', 'break', 'everybody', 'off', 'before', 'I', 'break', 'down']
    # tweet8 = ['Everyone', 'just', 'wait', 'now']
    # tweet9 = ['So', 'much', 'on', 'my', 'plate', 'now']
    # tweet10 = ['People', 'I', 'believed', 'in', 'they', "don't", 'even', 'show', 'their', 'face', 'now']
    # tweet11 = ['What', 'they', 'got', 'to', 'say', 'now?']
    # tweet12 = ['Nothing', 'they', 'can', 'say', 'now']
    # tweet13 = ['Nothing', 'really', 'changed,', 'but', 'still', 'they', 'look', 'at', 'me', 'away', 'now']
    # tweet14 = ['What', 'more', 'can', 'I', 'say', 'now?']
    # tweet15 = ['What', 'more', 'can', 'I', 'say', 'now?']
    # tweet16 = ['You', 'might', 'feel', 'like', 'nothing', 'was', 'the', 'same']
    # tweet17 = ['I', 'still', 'been', 'drinking', 'on', 'the', 'low']

    # tweet1 = ['I', 'might', 'be', 'too', 'strung', 'out', 'on', 'compliments,', 'overdosed', 'on', 'confidence']
    # tweet2 = ['Started', 'not', 'to', 'give', 'a', 'fuck', 'and', 'stop', 'fearing', 'the', 'consequence']
    # tweet3 = ['Drinking', 'every', 'night,', 'because', 'we', 'drink', 'to', 'my', 'accomplishments']
    # tweet4 = ['Faded', 'way', 'too', 'long', "I'm", 'floating', 'in', 'and', 'out', 'on', 'consciousness']
    # tweet5 = ['And', 'they', 'say', 'that', "I'm", 'back,', "I'd", 'agree', 'with', 'that']
    # tweet6 = ['I', 'just', 'take', 'my', 'time', 'with', 'all', 'this', 'shit,', 'I', 'still', 'believe', 'in', 'that']
    # tweet7 = ['I', 'had', 'someone', 'tell', 'me', 'I', 'fell', 'off,', 'ooh', 'I', 'needed', 'that']
    # tweet8 = ['And', 'they', 'wanna', 'see', 'me', 'pick', 'back', 'up,', 'well', "where'd", 'I', 'leave', 'it', 'at?']
    # tweet9 = ['']
    # tweet10 = ['I', 'know', 'I', 'exaggerated', 'things', 'now', 'I', 'got', 'it', 'like', 'that']
    # tweet11 = ['Tuck', 'my', 'napkin', 'in', 'my', 'shirt,', 'cuz', "I'm", 'just', "mobbin'", 'like', 'that']
    # tweet12 = ['You', 'know', 'good', 'and', 'well', 'that', 'you', "don't", 'wanna', 'problem', 'like', 'that']
    # tweet13 = ['You', 'gon', 'make', 'someone', 'around', 'me', 'catch', 'a', 'body', 'like', 'that']
    # tweet14 = ['']
    # tweet15 = ['No,', "don't", 'do', 'it', 'please', "don't", 'do', 'it']
    # tweet16 = ['Cuz', 'one', 'of', 'us', 'goes', 'in', 'and', 'we', 'all', 'go', 'through', 'it']
    # tweet17 = ['And', 'Drizzy', 'got', 'the', 'money']

    # tweet1 = ['I', 'met', 'this', 'girl', 'late', 'last', 'year']
    # tweet2 = ['She', 'said', "don't", 'you', 'worry', 'if', 'I', 'disappear']
    # tweet3 = ['I', 'told', 'her', "I'm", 'not', 'really', 'looking', 'for', 'another', 'mistake']
    # tweet4 = ['I', 'called', 'an', 'old', 'friend', 'thinking', 'that', 'the', 'trouble', 'would', 'wait']
    # tweet5 = ['But', 'then', 'I', 'jumped', 'right', 'in', 'a', 'week', 'later', 'returned']
    # tweet6 = ['I', 'reckon', 'she', 'was', 'only', 'looking', 'for', 'a', 'lover', 'to', 'burn']
    # tweet7 = ['But', 'I', 'gave', 'her', 'my', 'time,', 'for', 'two', 'or', 'three', 'nights']
    # tweet8 = ['Then', 'I', 'put', 'it', 'on', 'pause', 'until', 'the', 'moment', 'was', 'right']
    # tweet9 = ['I', 'went', 'away', 'for', 'months', 'until', 'our', 'paths', 'crossed', 'again']
    # tweet10 = ['She', 'told', 'me', 'I', 'was', 'never', 'looking', 'for', 'a', 'friend']
    # tweet11 = ['Maybe', 'you', 'can', 'swing', 'by', 'my', 'room', 'around', 'ten']
    # tweet12 = ['Baby', 'bring', 'the', 'lemon', 'and', 'a', 'bottle', 'of', 'gin']
    # tweet13 = ['Well', 'be', 'in', 'between', 'the', 'sheets', 'till', 'the', 'late', 'AM']
    # tweet14 = ['Baby', 'if', 'you', 'wanted', 'me', 'then', 'you', 'should', 'have', 'just', 'said']
    # tweet15 = ["She's", 'singing.']
    # tweet16 = ['']
    # tweet17 = ["Don't"]

    # tweet1 = ["Can't", 'be', "sleepin'"]
    # tweet2 = ['Keep', 'on', 'waking']
    # tweet3 = ['Is', 'that', 'the', 'woman', 'next', 'to', 'me?']
    # tweet4 = ['Guilt', 'is', 'burning']
    # tweet5 = ['Inside', "I'm", 'hurting']
    # tweet6 = ['This', "ain't", 'a', 'feeling', 'I', 'can', 'keep']
    # tweet7 = ['']
    # tweet8 = ['So', 'blame', 'it', 'on', 'the', 'night']
    # tweet9 = ["Don't", 'blame', 'it', 'on', 'me']
    # tweet10 = ["Don't", 'blame', 'it', 'on', 'me']
    # tweet11 = ['Blame', 'it', 'on', 'the', 'night']
    # tweet12 = ["Don't", 'blame', 'it', 'on', 'me']
    # tweet13 = ["Don't", 'blame', 'it', 'on', 'me']
    # tweet14 = ['']
    # tweet15 = ['Blame', 'it', 'on', 'the', 'night']
    # tweet16 = ["Don't", 'blame', 'it', 'on', 'me']
    # tweet17 = ["Don't", 'blame', 'it', 'on', 'me']

    # tweet1 = ['You', 'shout', 'it', 'out,']
    # tweet2 = ['But', 'I', "can't", 'hear', 'a', 'word', 'you', 'say']
    # tweet3 = ["I'm", 'talking', 'loud', 'not', 'saying', 'much']
    # tweet4 = ["I'm", 'criticized', 'but', 'all', 'your', 'bullets', 'ricochet']
    # tweet5 = ['Shoot', 'me', 'down,', 'but', 'I', 'get', 'up']
    # tweet6 = ['']
    # tweet7 = ["I'm", 'bulletproof,', 'nothing', 'to', 'lose']
    # tweet8 = ['Fire', 'away,', 'fire', 'away']
    # tweet9 = ['Ricochet,', 'you', 'take', 'your', 'aim']
    # tweet10 = ['Fire', 'away,', 'fire', 'away']
    # tweet11 = ['You', 'shoot', 'me', 'down', 'but', 'I', "won't", 'fall']
    # tweet12 = ['I', 'am', 'titanium']
    # tweet13 = ['You', 'shoot', 'me', 'down', 'but', 'I', "won't", 'fall']
    # tweet14 = ['I', 'am', 'titanium']
    # tweet15 = ['']
    # tweet16 = ['...']
    # tweet17 = ['']

    # tweet1 = ['Follow', 'the', 'Moskwa']
    # tweet2 = ['Down', 'to', 'Gorky', 'Park']
    # tweet3 = ['Listening', 'to', 'the', 'wind', 'of', 'change']
    # tweet4 = ['An', 'August', 'summer', 'night']
    # tweet5 = ['Soldiers', 'passing', 'by']
    # tweet6 = ['Listening', 'to', 'the', 'wind', 'of', 'change']
    # tweet7 = ['']
    # tweet8 = ['The', 'world', 'is', 'closing', 'in']
    # tweet9 = ['Did', 'you', 'ever', 'think']
    # tweet10 = ['That', 'we', 'could', 'be', 'so', 'close,', 'like', 'brothers']
    # tweet11 = ['The', "future's", 'in', 'the', 'air']
    # tweet12 = ['Can', 'feel', 'it', 'everywhere']
    # tweet13 = ['Blowing', 'with', 'the', 'wind', 'of', 'change']
    # tweet14 = ['']
    # tweet15 = ['Take', 'me', 'to', 'the', 'magic', 'of', 'the', 'moment']
    # tweet16 = ['On', 'a', 'glory', 'night']
    # tweet17 = ['Where', 'the', 'children', 'of', 'tomorrow', 'dream', 'away']

    # tweet1 = ['Sorry', 'to', 'disturb', 'you']
    # tweet2 = ['But', 'I', 'was', 'in', 'the', 'neighborhood']
    # tweet3 = ['About', 'a', 'friend,', "I've", 'her', 'picture']
    # tweet4 = ['Could', 'you', 'take', 'a', 'look?']
    # tweet5 = ['']
    # tweet6 = ['Oh,', 'I', 'appreciate', "you're", 'busy']
    # tweet7 = ['And', 'time', 'is', 'not', 'your', 'own']
    # tweet8 = ['Yeah,', 'maybe', 'it', 'would', 'be', 'better']
    # tweet9 = ['If', 'I', 'telephoned']
    # tweet10 = ['']
    # tweet11 = ['Carrie', "doesn't", 'live', 'here', 'anymore']
    # tweet12 = ['(Carrie)']
    # tweet13 = ['Carrie', 'used', 'to', 'room', 'on', 'the', 'second', 'floor']
    # tweet14 = ['(On', 'the', 'second)']
    # tweet15 = ['Sorry', 'that', 'she', 'left', 'no', 'forwarding', 'address']
    # tweet16 = ['That', 'was', 'known', 'to', 'me']
    # tweet17 = ['...']

    # tweet1 = ['Tell', 'me', 'what', 'you', 'want']
    # tweet2 = ['What', 'you', 'like']
    # tweet3 = ["It's", 'okay']
    # tweet4 = ["I'mma", 'little', 'curious,', 'too']
    # tweet5 = ['Tell', 'me', 'if', "it's", 'wrong']
    # tweet6 = ['If', "it's", 'right']
    # tweet7 = ['I', "don't", 'care']
    # tweet8 = ['I', 'can', 'keep', 'a', 'secret,', 'can', 'you?']
    # tweet9 = ['']
    # tweet10 = ['Got', 'my', 'mind', 'on', 'your', 'body']
    # tweet11 = ['And', 'your', 'body', 'on', 'my', 'mind']
    # tweet12 = ['Got', 'a', 'taste', 'for', 'the', 'cherry']
    # tweet13 = ['I', 'just', 'need', 'to', 'take', 'a', 'bite']
    # tweet14 = ['']
    # tweet15 = ["Don't", 'tell', 'your', 'mother']
    # tweet16 = ['Kiss', 'one', 'another']
    # tweet17 = ['Die', 'for', 'each', 'other']

    # tweet1 = ['In', 'the', 'town', 'where', 'I', 'was', 'born']
    # tweet2 = ['Lived', 'a', 'man', 'who', 'sailed', 'to', 'sea']
    # tweet3 = ['And', 'he', 'told', 'us', 'of', 'his', 'life']
    # tweet4 = ['In', 'the', 'land', 'of', 'submarines']
    # tweet5 = ['']
    # tweet6 = ['So', 'we', 'sailed', 'up', 'to', 'the', 'sun']
    # tweet7 = ['Till', 'we', 'found', 'the', 'sea', 'of', 'green']
    # tweet8 = ['And', 'we', 'lived', 'beneath', 'the', 'waves']
    # tweet9 = ['In', 'our', 'yellow', 'submarine']
    # tweet10 = ['']
    # tweet11 = ['We', 'all', 'live', 'in', 'a', 'yellow', 'submarine']
    # tweet12 = ['Yellow', 'submarine,', 'yellow', 'submarine']
    # tweet13 = ['We', 'all', 'live', 'in', 'a', 'yellow', 'submarine']
    # tweet14 = ['Yellow', 'submarine,', 'yellow', 'submarine']
    # tweet15 = ['']
    # tweet16 = ['And', 'our', 'friends', 'are', 'all', 'on', 'board']
    # tweet17 = ['...']

    # tweet1 = ['Rag', 'Doll', "livin'", 'in', 'a', 'movie']
    # tweet2 = ['Hot', 'tramp', "Daddy's", 'little', 'cutie']
    # tweet3 = ["You're", 'so', 'fine', "they'll", 'never', 'see', 'ya', "leavin'", 'by', 'the', 'back', 'door,', 'mam']
    # tweet4 = ['Hot', 'time', 'get', 'it', 'while', "it's", 'easy']
    # tweet5 = ["Don't", 'mind', 'come', 'on', 'up', 'and', 'see', 'me']
    # tweet6 = ['Rag', 'Doll', 'baby', "won't", 'you', 'do', 'me', 'like', 'you', 'done', 'before']
    # tweet7 = ['']
    # tweet8 = ["I'm", "feelin'", 'like', 'a', 'bad', 'boy']
    # tweet9 = ['Mm', 'just', 'a', 'like', 'a', 'bad', 'boy']
    # tweet10 = ["I'm", "rippin'", 'up', 'a', 'Rag', 'Doll']
    # tweet11 = ['Like', "throwin'", 'away', 'an', 'old', 'toy']
    # tweet12 = ['Some', "babe's", "talkin'", 'real', 'loud']
    # tweet13 = ["Talkin'", 'all', 'about', 'the', 'new', 'crowd']
    # tweet14 = ['Try', 'and', 'tell', 'me', 'of', 'an', 'old', 'dream']
    # tweet15 = ['A', 'new', 'version', 'of', 'the', 'old', 'scene']
    # tweet16 = ['Speak', 'easy', 'on', 'the', 'grape', 'vine']
    # tweet17 = ['Keep', "shufflin'", 'in', 'a', 'shoe', 'shine']
    
    # tweet1 = ['Baby,', 'are', 'you', 'down,', 'down,', 'down,', 'down,', 'down?']
    # tweet2 = ['Down,', 'down']
    # tweet3 = ['Even', 'if', 'the', 'sky', 'is', 'falling', 'down?']
    # tweet4 = ['Down,', 'down']
    # tweet5 = ['']
    # tweet6 = ['You', 'oughta', 'know']
    # tweet7 = ['Tonight', 'is', 'the', 'night', 'to', 'let', 'it', 'go']
    # tweet8 = ['Put', 'on', 'a', 'show']
    # tweet9 = ['I', 'wanna', 'see', 'how', 'you', 'lose', 'control']
    # tweet10 = ['']
    # tweet11 = ['So', 'leave', 'it', 'behind']
    # tweet12 = ["'Cause", 'we', 'have', 'a', 'night', 'to', 'get', 'away']
    # tweet13 = ['So', 'come', 'on', 'and', 'fly', 'with', 'me']
    # tweet14 = ['As', 'we', 'make', 'our', 'great', 'escape']
    # tweet15 = ['']
    # tweet16 = ['So', 'baby,', "don't", 'worry']
    # tweet17 = ['You', 'are', 'my', 'only']

    tweet1 = ["You'll", 'never', 'make', 'me', 'stay']
    tweet2 = ['So', 'take', 'your', 'weight', 'off', 'me']
    tweet3 = ['I', 'know', 'your', 'every', 'move']
    tweet4 = ['']
    tweet5 = ['So', "won't", 'you', 'just', 'let', 'me', 'be']
    tweet6 = ["I've", 'been', 'here', 'times', 'before']
    tweet7 = ['But', 'I', 'was', 'too', 'blind', 'to', 'see']
    tweet8 = ['That', 'you', 'seduce', 'every', 'men']
    tweet9 = ['This', 'time', 'you', "won't", 'seduce', 'me']
    tweet10 = ["She's", 'saying', "that's", 'ok']
    tweet11 = ['Hey', 'baby', 'do', 'what', 'you', 'please']
    tweet12 = ['I', 'have', 'the', 'stuff', 'that', 'you', 'want']
    tweet13 = ['']
    tweet14 = ['I', 'am', 'the', 'thing', 'that', 'you', 'need']
    tweet15 = ['She', 'looked', 'me', 'deep', 'in', 'the', 'eyes']
    tweet16 = ["She's", 'touchin', 'me', 'so', 'to', 'start']
    tweet17 = ['She', 'says', "there's", 'no', 'turnin', 'back']

    # Calculate the probabilities that the tweets are happy or sad
    # tweet1_happy_prob, tweet1_sad_prob = classifySentiment(tweet1, happy_log_probs, sad_log_probs)
    # tweet2_happy_prob, tweet2_sad_prob = classifySentiment(tweet2, happy_log_probs, sad_log_probs)
    # tweet3_happy_prob, tweet3_sad_prob = classifySentiment(tweet3, happy_log_probs, sad_log_probs)
    # tweet4_happy_prob, tweet4_sad_prob = classifySentiment(tweet4, happy_log_probs, sad_log_probs)
    # tweet5_happy_prob, tweet5_sad_prob = classifySentiment(tweet5, happy_log_probs, sad_log_probs)
    # tweet6_happy_prob, tweet6_sad_prob = classifySentiment(tweet6, happy_log_probs, sad_log_probs)
    # tweet7_happy_prob, tweet7_sad_prob = classifySentiment(tweet7, happy_log_probs, sad_log_probs)
    # tweet8_happy_prob, tweet8_sad_prob = classifySentiment(tweet8, happy_log_probs, sad_log_probs)
    # tweet9_happy_prob, tweet9_sad_prob = classifySentiment(tweet9, happy_log_probs, sad_log_probs)
    # tweet10_happy_prob, tweet10_sad_prob = classifySentiment(tweet10, happy_log_probs, sad_log_probs)
    # tweet11_happy_prob, tweet11_sad_prob = classifySentiment(tweet11, happy_log_probs, sad_log_probs)
    # tweet12_happy_prob, tweet12_sad_prob = classifySentiment(tweet12, happy_log_probs, sad_log_probs)
    # tweet13_happy_prob, tweet13_sad_prob = classifySentiment(tweet13, happy_log_probs, sad_log_probs)
    # tweet14_happy_prob, tweet14_sad_prob = classifySentiment(tweet14, happy_log_probs, sad_log_probs)
    # tweet15_happy_prob, tweet15_sad_prob = classifySentiment(tweet15, happy_log_probs, sad_log_probs)
    # tweet16_happy_prob, tweet16_sad_prob = classifySentiment(tweet16, happy_log_probs, sad_log_probs)
    # tweet17_happy_prob, tweet17_sad_prob = classifySentiment(tweet17, happy_log_probs, sad_log_probs)
    
    tweet1_workout_prob, tweet1_chill_prob = classifySentiment(tweet1, workout_log_probs, chill_log_probs)
    tweet2_workout_prob, tweet2_chill_prob = classifySentiment(tweet2, workout_log_probs, chill_log_probs)
    tweet3_workout_prob, tweet3_chill_prob = classifySentiment(tweet3, workout_log_probs, chill_log_probs)
    tweet4_workout_prob, tweet4_chill_prob = classifySentiment(tweet4, workout_log_probs, chill_log_probs)
    tweet5_workout_prob, tweet5_chill_prob = classifySentiment(tweet5, workout_log_probs, chill_log_probs)
    tweet6_workout_prob, tweet6_chill_prob = classifySentiment(tweet6, workout_log_probs, chill_log_probs)
    tweet7_workout_prob, tweet7_chill_prob = classifySentiment(tweet7, workout_log_probs, chill_log_probs)
    tweet8_workout_prob, tweet8_chill_prob = classifySentiment(tweet8, workout_log_probs, chill_log_probs)
    tweet9_workout_prob, tweet9_chill_prob = classifySentiment(tweet9, workout_log_probs, chill_log_probs)
    tweet10_workout_prob, tweet10_chill_prob = classifySentiment(tweet10, workout_log_probs, chill_log_probs)
    tweet11_workout_prob, tweet11_chill_prob = classifySentiment(tweet11, workout_log_probs, chill_log_probs)
    tweet12_workout_prob, tweet12_chill_prob = classifySentiment(tweet12, workout_log_probs, chill_log_probs)
    tweet13_workout_prob, tweet13_chill_prob = classifySentiment(tweet13, workout_log_probs, chill_log_probs)
    tweet14_workout_prob, tweet14_chill_prob = classifySentiment(tweet14, workout_log_probs, chill_log_probs)
    tweet15_workout_prob, tweet15_chill_prob = classifySentiment(tweet15, workout_log_probs, chill_log_probs)
    tweet16_workout_prob, tweet16_chill_prob = classifySentiment(tweet16, workout_log_probs, chill_log_probs)
    tweet17_workout_prob, tweet17_chill_prob = classifySentiment(tweet17, workout_log_probs, chill_log_probs)
    
    workout = (tweet1_workout_prob +tweet2_workout_prob + tweet3_workout_prob + tweet4_workout_prob + tweet5_workout_prob + tweet6_workout_prob + tweet7_workout_prob     + tweet8_workout_prob + tweet9_workout_prob + tweet10_workout_prob + tweet11_workout_prob + tweet12_workout_prob + tweet13_workout_prob
        + tweet14_workout_prob + tweet15_workout_prob + tweet16_workout_prob + tweet17_workout_prob) /17 

    # workout = workout + 0.0374

    # happy = (tweet1_happy_prob +tweet2_happy_prob + tweet3_happy_prob + tweet4_happy_prob + tweet5_happy_prob + tweet6_happy_prob + tweet7_happy_prob     + tweet8_happy_prob + tweet9_happy_prob + tweet10_happy_prob + tweet11_happy_prob + tweet12_happy_prob + tweet13_happy_prob
    #     + tweet14_happy_prob + tweet15_happy_prob + tweet16_happy_prob + tweet17_happy_prob) /17 
   
   # sad = (tweet1_sad_prob + tweet2_sad_prob + tweet3_sad_prob + tweet4_sad_prob + tweet5_sad_prob + tweet6_sad_prob + tweet7_sad_prob 
   # + tweet8_sad_prob + tweet9_sad_prob + tweet10_sad_prob + tweet11_sad_prob + tweet12_sad_prob + tweet13_sad_prob + tweet14_sad_prob + tweet15_sad_prob
   #+ tweet16_sad_prob + tweet17_sad_prob) /17 

    # print ("Happy = " + str(1-happy) )
    # print ("Sad = " + str(happy) )

    print ("Workout = " + str(workout) )
    print ("Chill = " + str(1-workout) )


if __name__ == '__main__':
    main()
